version: "3"
services:
  movies-battle-api:
    image: wallacerlima/movies-battle-api:1.0.0
    ports:
      - "8080:8080"
    networks:
      - network
  movies-api:
    image: wallacerlima/movies-api:1.0.0
    ports:
      - "8081:8081"
    networks:
      - network
  service-discovery:
    image: wallacerlima/service-discovery:1.0.0
    ports:
      - "8761:8761"
    networks:
      - network
networks:
  network:
    name: network