server:
   port: 8081

eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
   instance:
      preferIpAddress: true

spring:
   application:
      name: movies-battle-api
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      url: jdbc:h2:mem:moviesbattle
      username: admin
      password: admin
      driverClassName: org.h2.Driver
   jpa:
      show-sql: false
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   hibernate:
      format_sql: true
   flyway:
      locations: classpath:db/migration,classpath:db/testdata
movies:
   api:
      host: http://MOVIES-API