spring:
  application:
    name: movies-api

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
  instance:
    preferIpAddress: true

omdb:
  api:
    host: http://www.omdbapi.com
    key: 9b7950e7